
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">

<b>
<font face="verdana, geneva, tahoma, arial">Suburbs' Youth Meet City's Tough Justice</b></font>
<p>

<font face="verdana, geneva, tahoma, arial" size="-1">
By David Rohde<br> 
May 9, 2000<br>
New York Times<p>

Outraged parents from New Jersey and Long Island called it a travesty and declared Mayor Rudolph W.  Giuliani a tyrant. 
<p>
One Long Island 18-year-old, in tears, called his mother and complained that court holding cells were hot and overcrowded and that he could not eat the jail food that guards offered him.  And a 19-year-old vegetarian from Teaneck, N.J., said guards refused to provide her with a meatless sandwich, despite a sign saying they were available.
<p>
The mayor's zero tolerance approach to petty crime collided with a new opponent over the weekend -- marijuana-smoking suburbanites.  Police arrested 312 protesters, many of them young people from outside the city, at a marijuana legalization rally in Lower Manhattan on Saturday. 
<p>
The result was shock and indignation from protest organizers and dozens of suburban parents, who abruptly learned what some city dwellers, particularly minorities, have complained about for the last several years.
<p>
Under the Giuliani administration's continuing crackdown intended to improve quality of life, minor offenses ranging from smoking marijuana in public to jumping a turnstile typically result in a night in a sweltering, overcrowded and urine-soaked holding cell. 
<p>
"We don't even live in New York, but the way Giuliani's treating the homeless -- treating a kid as an adult -- I don't know," fumed Bill Walters, an equipment technician from the Jersey Shore who waited from 9 a.m.  Sunday until 1:45 a.m.  yesterday for his 17-year-old son to be released.  "Let's put his kid in jail and see how he feels.  If I lived in New York, I'd vote against him."
<p>
After the Millennium Marijuana March New York concluded in Battery Park on Saturday afternoon, some of the participants began smoking marijuana, and the police, who arrested 102 people in a similar event last year, rounded up almost a third of the 1,000 people they estimated participated in the march.  The vast majority were charged with smoking marijuana in public, a misdemeanor. 
<p>
The number of the arrests surprised march organizers, participants and dozens of parents who crowded the Manhattan Criminal Courts Building on Sunday, waiting for their children, some of whom were jailed for 36 hours, to be released.
<p>
Many parents were stunned to learn that New York police generally no longer issue court appearance tickets for minor crimes and that, as a result, they could not see their children for 24 hours. 
<p>
The parents were horrified by the conditions in the building and the sluggish pace of the process.  Those arrested complained of abusive treatment by officers who they said seemed to arrest people whether or not they were smoking, roughed-up some protesters and left others locked in sweltering vans for hours.
<p>
One woman, who would not give her name, said of the police: "They treated us like mass murderers.  They were rude." Two arrested protesters complained of being given tea without sugar. 
<p>
In most cases, those arrested on Saturday for smoking marijuana had no criminal record and so were not required to post bail and were told that the charges would be dropped if they are not arrested for a year. 
<p>
Detective Madelyne Dalindo, a police department spokeswoman, defended the arrests yesterday and said there was a reason why each person was held overnight.
<p>
One might have lacked valid identification, for example, and another might have had an outstanding warrant, she said. </p>

<p>Kate Morgan, one of the march organizers, said leaders of her group, Cures Not wars, told the participants not to smoke marijuana.  She said the protesters planned to file a lawsuit against the city. 
<p>
Tom Antenen, a spokesman for the City Department of Corrections, said that water, food and telephones were available to prisoners once they were put in holding cells.
<p>
David Bookstaver, a spokesman for the court system, said that court workers and judges made a "Herculean effort" to process a huge number of arrests.
<p>
Judges Eileen Koretz and James Sullivan arraigned 400 defendants on Sunday evening, a record for two judges, he said, and court personnel worked until 3 a.m.  to process the backlog. 
<p>
David Kapner, the arraignment supervisor for the Legal Aid Society who worked on the arrest cases Sunday night, said the complaints of petty arrests and mistreatment were nothing new.  Mr.  Kapner said the city's poor have long borne the brunt of the quality-of-life crackdown, and when more affluent people experience it they are usually stunned by the treatment and conditions.</font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
