
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">

<b>
<font face="verdana, geneva, tahoma, arial">Smoke a Joint, Lose Your Loan</b></font>
<p>

<font face="verdana, geneva, tahoma, arial" size="-1">
By Jake Ginsky<br> 
May 18, 2000<br>
Mother Jones Magazine

<p><b>Starting this July, a new law will cut off federal financial aid to students convicted of drug offenses.</b></p>
<p>"Anne" is the type of success story that makes college admissions officers smile. She had little money growing up, but with the help of federal loans and a lot of sweat has managed to afford an education at Ohio's Antioch College. In addition to attending school full-time, she currently works two jobs, one of which involves teaching drama to grade-school children. If all goes well, she will graduate at the end of the summer with a degree in theater. </p>

<p>But to the federal government, Anne is a campus undesirable. In early May, police caught her with an empty one-hit pipe containing residue from the marijuana she occasionally smokes, and now she's awaiting trial. The charge is only misdemeanor drug possession -- but if she's convicted, Anne may lose her federal Pell Grant, which she depends on to pay for school.</p> 

 
<p>That's thanks to a new law kicking into effect July 1, which requires the federal government to deny or delay all financial aid to students with a drug conviction in the past year. </p>

<p>"Without federal aid, I couldn't go to school," said Anne. "It's just utterly ridiculous to think that I've worked this long to get here, and now this new law might blow me out of the water." </p>

<p>Passed into law two years ago, the no-loans-for-stoners provision of the Higher Education Act is now drawing heavy criticism from many legislators, activist groups, and educators, who say it will unfairly deprive serious students of an education and inherently discriminate against minorities and low-income people. </p>

<p>So far, of the roughly 5 million applications the Education Department has processed for the 2000-2001 school year, only about 3,200 applicants will either be refused aid entirely or have it delayed because of a drug conviction. But some 10 million students apply for federal financial aid each year; and according to the federal government's own most recent estimates, some 27 percent of all Americans aged 18 to 25 have used illegal drugs in the past year. That means the new law could potentially affect hundreds of thousands, even millions, of students. </p>

<p>"It's indicative of this obsession with being overly punitive with regard to the use of drugs," says Rep. Barney Frank, D-Mass., who has introduced legislation to overturn the loan ban. "You single out drug offenders, so apparently armed robbery is not as serious an offense." </p>

<p>Critics say the issue is not just one of numbers, but also of basic fairness. Many students will be penalized for simple bad luck. "It's kind of just hit-or-miss as far as who gets busted [for drug use]," says Alex Kreit of Students for Sensible Drug Policy at Hampshire College. </p>

And because it singles out <I>convicted </I>drug offenders, many say the loan ban provision will hurt
minorities -- particularly blacks -- the most. African Americans constitute 59
percent of those convicted of drug offenses, even though African Americans
and whites have about the same rate of drug use, according to the 
<a href="http://www.civilrights.org/policy_and_legislation/pl_issues/criminal_justice/index.html" target="_blank">Leadership Conference on Civil Rights</a>. 

<p>In addition, critics say, the 
law discriminates against poor people, since they are obviously most 
in need of financial aid.

<p>"Wealthier kids are more likely to have adequate counsel in court, and
they're more likely to get a better plea deal," says Adam Smith, associate
director of the <a href="http://www.drcnet.org"><font color="#cc0000">Drug Reform Coordination Network</font></a>. "Even if they do end up
with a drug conviction, they're not going to be dependent on financial aid to
get their education anyway."

<p>Angela Flood, a spokesperson for Rep. Mark Souder, R-Ind., who sponsored the
legislation, said the provision will help ensure a healthier 
learning environment. "[Financial aid] is a privilege, not a right," 
she said.

<p>Flood also pointed to a provision that exempts drug offenders from 
the loan provision if they've completed an "acceptable drug 
rehabilitation program." But
critics say that since the law will mostly affect minor drug offenders,
requiring that they attend often-costly rehab programs to get financial assistance is unfair in
itself.

<p>Aside from the ethical issues it raises, the provision is proving to be an
administrative migraine. Students are supposed to confess to their drug use in question 28 of the federal student aid application form. But that question was left blank on about 20 
percent of the first wave of  applications -- not because 
applicants were dodging the question but simply because many didn't 
understand it, according to Karen Freeman,
communications director for Student Financial Assistance. Initially, the page-long "worksheet" (since amended) 
was worded in such bewildering language that only someone on serious drugs 
could've hoped to make sense of it. To avoid bottlenecking the 
system, the department processed the incomplete forms without 
penalizing any applicants.

<p>An even greater problem officials face is how to tell whether those who do
answer question 28 are telling the truth. There is no national database of
drug convictions. "It is difficult to enforce," admits Freeman. "Is it really worth
slowing down the system for the millions of applicants who have absolutely no
business with a drug offense to find the very small percentage who are lying?"

<p>Still, Freeman says that students who lie on their aid forms do stand a 
chance of being caught -- a crime that can bring up to a $10,000 fine 
or imprisonment.

<p>Last year, Rep. Frank introduced a bill to repeal the loan-ban 
provision. But, despite several on-campus rallies supporting the bill, it appears doomed, 
according to several members of the Education and Workforce 
Committee, where it now sits. "My colleagues are terrified of being accused of being 
soft on drugs," Frank said. "I think this is one area where the 
public is way ahead of them."

<p>Assuming Frank's bill does die, dedicated students such as Anne will 
simply have to hope for the best.

<p>"It's not like I'm a violent criminal or anything," Anne says. "I'm not out on the streets raping and killing people. All I want is to get through these last three months and get my degree."
</font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
