
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">

<font face="geneva,verdana,tahoma, sans-serif">
<b>Let us know which ads you would like to see in New York and San Francisco!  Vote for your favorite!</b>
</font><p>
<font face="geneva,verdana,arial" size="-1">
Change the Climate is planning transit and outdoor advertising in New York City and San Francisco, CA.  Be sure and vote for your favorite ad below.  You just might see it on a billboard or bus shelter soon! 
</font><p>
<font face="geneva,verdana,arial" size="-1">
<b>New York City</b><br>
Which ad would you like to see in New York City?
</font>
<!-- BEGIN MyPoll.Net HTML CODE --> 
<form ACTION="http://www.mypoll.net/cgi-bin/vote" METHOD="POST" target="_blank">
<input type="hidden" name="id" value="16098">
<table border="0" width="525" cellpadding="4" cellspacing="0">
<tr>
<td><input type="radio" name="vote" value="1"></td>
<td align="center"><img src="../images/alcohol2.jpg" height="60" width="468" alt="Change the Climate" border="1"></td>
</tr>
<tr>
<td><input type="radio" name="vote" value="2"></td>
<td align="center"><img src="../images/political.jpg" height="60" width="468" alt="Change the Climate" border="1"></td>
</tr>
<tr>
<td><input type="radio" name="vote" value="3"></td>
<td align="center"><img src="../images/crowd.gif" height="60" width="468" alt="Change the Climate" border="1"></td>
</tr>
<tr>
<td colspan="2" align="center"><input type="submit" name="submit" value="vote!"><p>
<a href="http://www.mypoll.net/cgi-bin/vote?id=16098" target="_blank"><font face="geneva,verdana,arial" size="-2">current results</font></a>
</td>
</tr>
</table>
</form>
<p>
<p>
<font face="geneva,verdana,arial" size="-1">
<b>San Francisco</b><br>
Which ad would you like to see in San Francisco?
</font>
<p>
<!-- BEGIN MyPoll.Net HTML CODE --> 
<form ACTION="http://www.mypoll.net/cgi-bin/vote" METHOD="POST" target="_blank">
<input type="hidden" name="id" value="16099">
<table border="0" width="525" cellpadding="4" cellspacing="0">
<tr>
<td><input type="radio" name="vote" value="1"></td>
<td align="center"><img src="../images/cancer.jpg" height="60" width="468" alt="Change the Climate" border="1"></td>
</tr>
<tr>
<td><input type="radio" name="vote" value="2"></td>
<td align="center"><img src="../images/governor.gif" height="60" width="468" alt="Change the Climate" border="1"></td>
</tr>
<tr>
<td><input type="radio" name="vote" value="3"></td>
<td align="center"><img src="../images/political.jpg" height="60" width="468" alt="Change the Climate" border="1"></td>
</tr>
<tr>
<td colspan="2" align="center"><input type="submit" name="submit" value="vote!"><p>
<a href="http://www.mypoll.net/cgi-bin/vote?id=16099" target="_blank"><font face="geneva,verdana,arial" size="-2">current results</font></a>
</td>
</tr>
</table>
</form>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
