
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">

<font face="geneva,verdana,tahoma, sans-serif">
<b>Advertising For Change</b>
<p>
by Pete Brady<br>
cannabisculture.com
</font><p>
<font face="geneva,verdana,arial" size="-1"> 
<img src="../images/busad2.jpg" height="260" width="312" alt="Change the Climate" align="right" hspace="6" vspace="6">

It isn't normal for Americans to see advertisements seeking to change the climate by inserting common sense into the debate about marijuana use. But three non-profit organizations - NORML, Common Sense for Drug Policy, and Change the Climate, Inc. - are sponsoring savvy ad campaigns that challenge the war on pot.
<p>
<b>Changing the Climate</b>
<p>
In January, Change the Climate took advantage of a Washington DC public transit system policy, which gives big discounts to non-profits seeking advertising space in the system's subway stations and buses.
<p>
Joe White, a Massachusetts-based marketing and public relations pro who works with a consortium of one hundred social change organizations called The Share Group, founded Change the Climate in 1999.
<p>
"On the way to a track meet, my 17-year-old son asked me why adults lie to kids about marijuana," White explained. "I'd been hearing about medical marijuana initiatives, and my son told me that propagandists at school were still claiming that marijuana was like heroin. I decided to do some professional marketing to initiate a dialogue about this problem."
<p>
White raised money, then approached DC Metro, Boston's Massachusetts Bay Transportation Authority (MBTA), and some billboard companies. MBTA and DC Metro refused to run the ads, saying they promoted drug use.
<p>
The billboard companies also turned down the ads, telling White that local authorities control billboard placement and would likely take punitive action against his messages.
<p>
Represented by the American Civil Liberties Union, White sued.
<p>
DC Metro relented, so White spent nearly $10,000 to print paper ads and purchase space for them on 10 subway platforms. His ads also appear inside 50 buses and on the outside of 500 buses traveling in Washington, DC, Maryland and Northern Virginia.
<p>
However, Massachusetts Republican Governor Paul Celluci refused to allow MBTA to run the ads, even though his senior staff recommended that he settle the lawsuit out of court.
<p>
"According to the Boston Herald, Celluci went nuts over our ads," White said. "We're pressing forward, asking for six months free ad space and punitive damages. They've lost free speech cases before. They'll lose this one."
<p>
The DC ads are stark and compelling. One features a young woman asking, "Why do kids go to jail for doing what politicians did when they were young?" Another ad shows two cops in front of an American flag. The ad text says police are "too valuable" to waste time arresting pot people "when real criminals are on the loose." Another ad shows a cancer-stricken businessman who smokes pot to help him tolerate the effects of chemotherapy.
<p>
"We're raising money to take this campaign to Chicago, New York and other cities," White says. "The goal is to reach real people, not politicians who are afraid to even talk about this issue, and get the public to realize that they'll be the ones to change our counterproductive marijuana policies, with their lobbying and with their votes."
<p>
<b>Free speech is NORML</b>
<p>
NORML director Keith Stroup says White is a welcome ally in the advertising war for marijuana law reform.
<p>
"Joe worked for us as a fundraiser, market researcher and consultant," Stroup said. "I'm happy he's still making a difference."
<p>
NORML is also making a difference. Stroup's organization just spent $50,000 buying newspaper and radio ads in New Mexico, and Stroup recently returned from lobbying trips in New Mexico, where he was accompanied by NORML boardmembers Dr John Morgan and Dr Lester Grinspoon.
<p>
Stroup says he and the docs will likely testify at New Mexican legislative hearings.
<p>
"It's a wonderful opportunity to make some real progress," Stroup explained, "We've got a courageous Republican governor who supports us and has general political support, so he's not just out on a limb. We've got two bills coming up – one on medical marijuana, the other on decriminalization. This is less than a tenth of the advertising budget we've allocated this year. We intend to spend $600,000 on ad campaigns."
<p>
NORML's New Mexico newspaper ads feature a picture of three 1920's style gangsters. The message: prohibition didn't work for alcohol, and it isn't working for marijuana either.
<p>
The organization's 60-second radio ads ran one hundred times on six stations in three weeks. Their message: 76 million Americans have smoked marijuana, and none of them deserve to go to jail.
<p>
"These are a test that will gauge the effectiveness of our messages," Stroup says. "We've got professionals looking at the results, then we'll determine where and how to advertise next. Maybe we'll go to target communities, do an opinion survey about pot, run some ads, then do another survey and see if we have changed opinion. If we can do that with a specific amount of money, then we can credibly tell people how much it will cost to change opinion across America. I'd like to make a big difference in the next two election cycles."
<p>
Washington, DC-based Common Sense for Drug Policy (CSDP) is also in the advertising business.
<p>
CSDP director Kevin Zeese says his organization has run ads in national magazines, such as New Republic, The Nation, Reason, and the Weekly Standard.
<p>
CSDP's ads are clever and wide-ranging. A recent advert featured quotes from President George W Bush, indicating that Bush views drug use as a medical problem rather than a crime. Zeese's ads also targeted former drug czar Barry McCaffrey, drug war hypocrisy, and drug warrior's dishonesty. Some of CSDP's ads have been co-sponsored by establishment organizations, such as the National Black Police Association.
<p>
White, Stroup and Zeese say their professional ad campaigns avoid "preaching to the choir" by targeting citizens who aren't already aware of the costs and injustices of the drug war. They're optimistic that pro-reform advertising is effective, but they admit to worrying about one problem that could impede their efforts: lack of money.
<p>
"We got a good deal in DC," White says, "but the campaign will cost more elsewhere. It's worth it. America's too good a country to tolerate marijuana policies that do nothing but waste money, destroy kids' faith in government, and cause suffering."
</font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
