
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">

<b>
<font face="verdana, geneva, tahoma, arial">Articles Archive</b></font>
<p>

<font face="verdana, geneva, tahoma, arial" size="-1">
<table width="100%" border="0" cellspacing="0" cellpadding="4">
		 <tr>
 
            
            <td colspan="2"><b><font face="verdana, geneva, tahoma, arial" size="-1">The Boston Transit Campaign Coverage</b></font></td>

          </tr>
<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">03/01/01</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.reason.com/0103/ci.js.moving.html" target="_blank">Moving Words</a> (Reason.com)</font></td>
          </tr>
<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">01/04/01</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="boston.phtml">Metro Accepts Marijuana Ad Banned in Boston</a> (Washington Post)</font></td>
          </tr>

<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">09/28/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="editorial.phtml">Joe White's Opinion in Response to Boston Herald Editorial
  </a></font></td>
          </tr>
		
				<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">09/22/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.bostonherald.com/news/opinion/edtb09222000.htm" target="_blank">Cellucci Just Says No -- Editorial
  </a> (Boston Herald)</font></td>
          </tr>
		  
		 	<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">09/21/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.mapinc.org/drugnews/v00/n1410/a08.html?244790" target="_blank">Gov Sticks by Pot Ad Fight: Forbits MBTA to Settle Federal Suit  </a> (Boston Herald)</font></td>
          </tr>

<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">06/12/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.npr.org/ramfiles/me/20000612.me.05.rmm">Listen to the NPR's Morning Edition Report About the Lawsuit.</a> <font size="1">Requires the <a HREF="http://www.npr.org/inside/realaudio.html" target="_blank">RealAudio Player</a></font></td>
          </tr>
<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">05/22/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.freedomforum.org/news/2000/05/2000-05-22-02.asp" target="_blank">Pro-marijuana group sues transit agency for refusing ads</a> (Associated Press)</font></td>
          </tr>
		  
		<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">05/19/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.bostonherald.com/news/local_regional/mbta05192000.htm" target="_blank"> MBTA Sued for Nixing Pro-marijuana Ads</a> (Boston Herald)</font></td>
          </tr>
		  
<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">05/19/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.mapinc.org/drugnews/v00/n702/a10.html?217649" target="_blank">MBTA Under Fire for Rejecting Ads on Marijuana</a> (Boston Globe)</font></td>
          </tr>  
 <tr> 
            <td colspan="2">&nbsp;</td>
          </tr>
		  
		 <tr> 
            <td colspan="2"><font face="verdana, geneva, tahoma, arial" size="-1"><b>Other Articles:</b></font></td>
          </tr>
<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">03/20/01</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2">
<a href="http://www.lp.org/lpnews/0103/forfeiture.html" target="_blank">Asset Forfeiture: Looting America</a></font></td>
          </tr>
<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">03/08/01</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2">
<a href="whouston.phtml">Whitney Houston's Drug Case Dropped</a> (Associated Press)</font></td>
          </tr>

    <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">02/26/01</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2">
<a href="http://www.washingtonpost.com/wp-dyn/articles/A54917-2001Feb25.html" target="_blank">Our Duplicitous Drug Dialogues</a> (Washington Post)</font></td>
          </tr>
  <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">01/05/01</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2">
<a href="http://adlatina.com/pages/noticias/vernota.php3?id=1207" target="_blank">Una campaña en pro de la marihuana en Washington</a><br>Use <a href="http://babel.altavista.com/translate.dyn" target="_blank">Babel Fish</a> to translate.</font></td>
          </tr>		
  		
  
  <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">11/29/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2">
<a href="http://www.washingtonpost.com/wp-dyn/articles/A4740-2000Nov29.html" target="_blank">Robert Downey's Problem--and Ours</a> (Washington Post)</font></td>
          </tr>

  
		  		<tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">09/27/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.nytimes.com/2000/09/27/national/27LESS.html" target="_blank">Reality Check Is Overdue in Preventing Drug Abuse</a> (NY Times)</font></td>
          </tr>
	
        <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">05/18/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="051800.phtml">Smoke a Joint, Lose Your Loan</a> (Mother Jones Magazine)</font></td>
          </tr>
					   <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">05/09/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="050900.phtml">Suburbs' Youth Meet City's Tough Justice</a> (New York Times)</font></td>
          </tr>
          <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">02/05/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.mapinc.org/drugnews/v00/n161/a09.html" target="_blank">Ten 
              Year Olds on Drugs</a> (Washington Post)</font></td>
          </tr>
          <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">02/04/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.mapinc.org/drugnews/v00/n160/a03.html" target="_blank">Reefer 
              Madness: The War On Pot </a>(Vancouver Sun -- CN BC)</font></td>
          </tr>
          <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">02/04/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.mapinc.org/drugnews/v00/n161/a02.html" target="_blank">3 
              Schools To Start Hair Drug Tests New</a> (Orleans Times-Picayune--LA)</font></td>
          </tr>
          <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">02/03/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.mapinc.org/drugnews/v00/n163/a06.html" target="_blank">Marijuana 
              Reports Need Unbiased Eye</a> (Burlington Free Press--VT)</font></td>
          </tr>
          <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">01/30/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.mapinc.org/drugnews/v00/n140/a01.html" target="_blank">Drugs 
              in Rural America</a> (The Blade)</font></td>
          </tr>
          <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">01/22/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.mapinc.org/drugnews/v00/n098/a10.html" target="_blank">Aid 
              Money Targets Certain Demographic Groups</a> (Arizona Republic )</font></td>
          </tr>
          <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">01/19/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.nydailynews.com/2000-01-19/News_and_Views/City_Beat/a-53994.asp" target="_blank">Cutoff 
              of Parental Rights Climbs</a> (Daily News)</font></td>
          </tr>
          <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">01/19/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.washingtonpost.com/wp-srv/WPlate/2000-01/19/165l-011900-idx.html" target="_blank">Networks 
              Get Anti-Drug Guidelines</a> (Washington Post)</font></td>
          </tr>
          <tr> 
            <td><font face="verdana, geneva, tahoma, arial" size="-1">01/15/00</font></td>
            <td><font face="verdana, geneva, tahoma, arial" size="-2"><a href="http://www.washingtonpost.com/wp-srv/WPlate/2000-01/15/030l-011500-idx.html" target="_blank">Drugs, 
              TV and Propaganda</a> (Washington Post)</font></td>
          </tr>
   </table>
</font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
