
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">
<font face="geneva,verdana,tahoma, sans-serif">
<b>Paul Cellucci</b></font><br>

<font face="geneva,verdana,tahoma, sans-serif" size="-1">Ex-governor enters Hall of Shame</font>

<p>
<font face="geneva,verdana,arial" size="-1">
<a href="http://www.bostonphoenix.com/boston/news_features/top/features/documents/01692187.htm" target="_blank">Bostonphoenix.com</a><p>

<img src="../images/cellucci.gif" width="161" height="240" alt="Paul Cellucci" align="left" hspace="8" vspace="4"><p>After having been dishonored with Muzzles in 1998 and 1999, the right honorable ambassador to Canada becomes our first three-time winner and thus the first inductee into our Hall of Shame. The former governor will not be eligible for future Muzzles on the theory that it’s unfair to expect others to compete against someone with such an awe-inspiring record.</p>

<p>Cellucci’s latest transgression against free speech took place last September. Change the Climate, a Greenfield-based group that favors the decriminalization of marijuana, sought to place $25,000 worth of ads on the MBTA’s buses, trains, and stations. One ad read, "Why do kids go to jail for doing what politicians did when they were young? Tell us the truth." Another: "I’ve got three great kids. I don’t want them to smoke pot.... But I know jail is a lot more dangerous than smoking pot."</p>

<p>The T rejected the ads, despite their entirely political nature. "We have an obligation to our riders," MBTA spokesman Brian Pedro told the Associated Press. "In a subway car you can’t change the channel." (Recycled-quote watch: this past March, when the T refused to run a racy ad for the movie Tomcats, Pedro told the AP: "We have a responsibility to our passengers. They can’t change the channel if they are on a bus.")</p>

<p>After the pot-decriminalization ads were turned down, Change the Climate lawyer Harvey Schwartz, noting that the T had lost previous lawsuits challenging its retrograde advertising policies (as when a federal court ruled that its refusal to post the AIDS Action Committee’s condom ads was unconstitutional), responded, "The MBTA is a public entity. It can’t pick and choose which political beliefs it will support and not support." And he sued.</p>
<p>
Enter Cellucci. Last September, the then-still-governor told the Boston Herald he was insisting that the MBTA hang tough, saying, "I’m not going to settle the case. I want them to fight. Why should a government entity be forced to put up a message that may be harmful to children? That’s ridiculous."</p>
<p>
Subway censorship wasn’t Cellucci’s only anti-free-speech action last year. Also in September, he refused to sign a bill that would have allowed condominium owners to fly flags even if their condo associations forbade it; Cellucci said he would be happy to protect Old Glory, but that was as far as he was willing to go. (You never know when someone might want to fly the hammer and sickle next to the hot tub.) Cellucci also insensitively whined that gay and lesbian advocates had "blown out of proportion" a proposal that thousands of state employees disclose whether they had ever been charged with any one of a range of sex-related crimes, including sodomy. (Earth to Cellucci: under Massachusetts’s archaic laws, most forms of gay sex are decidedly illegal.) And Cellucci was a driving force behind a state constitutional amendment to ban prison inmates from voting, which is the subject of yet another Muzzle Award this year.</p>
<p>
Fortunately for Cellucci, his political patron, George W. Bush, became president. And fortunately for Massachusetts, Cellucci left the scene, never again to suppress free speech here.
 </p>
</font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
