
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">
<img src="../images/post.gif" width="120" height="68" alt="The Washington Post"><p>
<b>
<font face="verdana, geneva, tahoma, arial">Our Duplicitous Drug Dialogues</b></font>
<p>

<font face="verdana, geneva, tahoma, arial" size="-1">
<b>By Jonathan Zimmerman</b>
<p>

Just before her son's 16th birthday, Isabel Loxley discovered that he was smoking cannabis. She confiscated his supply. But what to do next, as a liberal parent - ground him, or just hand the joints back? 
<p>

It was his ghostly pallor and refusal to eat supper that gave him away. Adam thought he was sick and suggested he lie down while the others ate. Later, after clearing up, Adam went up to his room - two flights, to the top of the house - to see if he was OK. Forgetting to knock, Adam opened the door to find Joe on his bed, joint alight. 
A few days short of his 16th birthday, we were having to deal with our son's cannabis use. It came as a surprise, despite the fact that we know the statistics on teenagers and drugs. There had been no telltale signs: no mood swings, no secretive behaviour, no cash shortages, no enlarged pupils - not even a whiff of smoke. Of course, we had talked about our attitude towards drugs and how we might deal with the issue when it arose. We just hadn't expected it to arise yet. A few weeks earlier, I had confidently, smugly told a colleague that my son was sailing through a trouble-free adolescence. 
<p>
Of course, we were not alone. Surveys in the 1990s showed that between a quarter and a third of 14- and 15-year-olds had tried drugs; and the number rose steeply after 16. Jack Straw's teenage son was caught offering it for sale. When Ann Widdecombe proposed a crackdown on users, seven shadow cabinet members said they had tried it. Last week, the government announced that police cautions for possession would no longer be part of a criminal record - a sign of changing attitudes to cannabis use. 
<p>
Adam called me as I was driving home. "There's something you should know," he announced - words guaranteed to sink the heart at the end of a long day at work. Briefly, he told me what had happened. "I've had a mellow chat to him already," Adam joked, making me giggle down the mobile, "but I said we'd talk to him properly together when you get home." We agreed to discuss it alone first to establish a united front. 
<p>
I had half an hour in the car to work out my response. Adam and I had both smoked dope in the past, and had tried different drugs. But it was mostly in pre-parenthood days. Since that cloak of responsibility had settled on us, we had shared a joint at a party on less than a handful of occasions. We support decriminalisation of cannabis, and we both believe it is less harmful than tobacco or alcohol. We know that almost every teenager will try it, and we don't buy the argument that it leads inevitably to harder, more dangerous drugs. 
<p>
But this was our son, our baby. Surely that was different? Whenever I had ventured a liberal line on teenagers and dope with family or friends, I had been warned that I would feel a lot less liberal when it came to my own children. In that half-hour in the car, I first waited for an instinctive gut reaction to the news. When none came, I tried out various responses on myself. It felt like testing for pain, prodding and poking at myself, waiting for a sharp jolt that I could label. 
<p>
Was I shocked? Not really. I knew too much about the prevalence of cannabis smoking among teenagers. Was I angry? Not really. I remembered too much of my own teenage years for that. Alarmed? Sad? Trust betrayed? Not really. Curiously, I felt almost nothing. 
<p>
When I arrived home, I found Joe lying on the sofa, looking sheepish, with anxious eyes that betrayed his expectation of trouble. Adam was in the kitchen, sitting at the table with five - five! - joints in front of him. On being caught with a lit joint and an open bedroom window, Joe had quickly confessed: he had been smoking for about four months; he bought dope from a friend's older brother; he never smoked anywhere near school. The five spliffs were inside a cassette case lying on a chair next to his bed. Adam spotted them straight away and had brought the evidence to show me. 
<p>
We looked at the joints, then looked at each other. "He rolls quite a good joint for a 15-year-old," said Adam wryly. "What are we going to say?" Within minutes, we established common ground. Neither of us thought this was a heinous crime, yet we didn't feel that we could give Joe our blessing. As Adam split open one of the joints to see how much dope was inside, I felt - at last - a proper parental response. It was, of course, mostly tobacco - the substance to which Joe had been consistently opposed throughout his adolescence, and one which I felt was far more dangerous and addictive than cannabis. We agreed a number of points to put to Joe, and called him in. 
<p>
It's a strange thing, being a parent. You remember your own teenage years all too clearly - the injustices, the humiliations, the rows, the bollockings, the slammed doors, the fury - and yet, inevitably, you find yourself 25 years down the line adopting the role of prosecutor, judge, executioner. You ask the same questions - "What time will you be home? Where are you going? Who with?" - that your parents asked you. And you hear your own teenage voice reply - "Don't know. Why do you need to know? Leave me alone." As Joe came in the room, my mind went straight back to similar painful sessions with my own parents, when the last thing you want to do is "talk it through", but you know that is the minimum price you must pay for your transgression. 
<p>
So the three of us sat round the spliffs and talked it through. Actually, Adam and I did most of the talking. First, it's illegal, we said. You may not agree with that, and we may not either, but that's a fact: if you get caught, you'll be in trouble with the law. Second, if you smoke at school, or have it with you, and get caught, you will be expelled. Third, if you are buying dope from someone, sooner or later that person will offer you something different to try - and that's the point where we might be less tolerant. Fourth, you are more likely to come to harm from the tobacco in the joints than from the dope. Fifth, it's expensive and you have to decide what you want to spend your money on. Sixth, if you ever offer it to your little sister, we will break your legs. And so on. 
<p>
Joe said little, apart from telling us that "everybody" at his leafy-suburb school smoked dope. Really everybody? He qualified the figure to 90% of his friends and contemporaries. 
<p>
After 20 minutes of trying to ram home the dangers of harder drugs and tobacco, we asked Joe to go away and think long and hard about what we had said. We stared at each other, and at the spliffs on the table. Had we handled it right? Impossible to say. 
<p>
After about three minutes, the door opened and Joe's face poked round. "Are you going to give me my dope back?" he asked, tilting his head at the joints. We handed them over. 
<p>
Did we do the right thing? What is "the right thing", anyway? It's hard to navigate your way through parenthood, to know how much space to give; how protective or how tough to be. For something that so many people do, and so many have done down the years, parenthood has no definitive rules. The compass-points that guided my parents' generation are not necessarily relevant today, but neither does the experience of one's peer group always accurately reflect one's own rational views on a particular issue. So we muddle through, try not to be hypocritical, and hope for the best. 
<p>
Two weeks after our discovery, Joe doesn't seem any different from the loving, happy, intelligent, well-balanced teenager he was before. That said, when he burst through the door at the weekend, enveloped me then Adam in giant bear hugs, ate two bananas in quick succession, and launched into a long and rambling account of his plans to travel the world in a camper van, Adam caught my eye behind Joe's back. 
<p>
"He's stoned," he mouthed. 
<p>
<li>All names have been changed.</li>
</font>
<p align="center">
<font face="verdana, geneva, tahoma, arial" size="-2">
Article is &copy; 2001 Guardian Newspapers Limited.
</font></p>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
