
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">

<b>
<font face="verdana, geneva, tahoma, arial">Dear Editor:</b></font>
<p>

<font face="verdana, geneva, tahoma, arial" size="-1">
<p>While we were delighted to learn from your September 21 article that Governor Cellucci "blew his stack" about our First Amendment lawsuit against the MBTA, the ad copy that you quoted in the story and again in the September 22 editorial is wrong.  Your article stated that "One ad depicts a mother saying, 'Let's be honest . . . marijuana is not cocaine or heroin."  That is not correct and you should have asked for copies of the ads before you printed the article and your editorial.  I assumed that the first rule of journalism was to check your sources.</p>
 
<p>For your readers' information, one ad depicts a teenager saying "It's not cool to smoke marijuana, but we're not stupid ya know.  Marijuana is not cocaine or heroin.  Tell us the truth . . . "  Clearly Change the Climate is not promoting marijuana use; as parents we find marijuana use by kids unacceptable.  </p>
 
<p>But why should teenagers believe anything adults say when government advertising presents marijuana in the same genre as heroin and other hard drugs?  Marijuana and heroin are Schedule 1 drugs (most dangerous) as classified by the federal government.  This is just plain stupid and we should tell the truth.  After all, most of your readers have tried marijuana and so have lots of teenagers.  Let's regain adult and government credibility by using a little honesty.  This is not the same thing as promoting marijuana use or saying it is OK for kids -- it's not!
 </p>
<p>        Finally, our ad with the mother says "I have three great kids.  I love them more than anything.  I don't want them to smoke pot.  But I know jail is a lot more dangerous than smoking pot."  Can you find me a mother who wants her child to spend one minute in jail with rapists, murderers, pedophiles and other hard core thugs for smoking a little marijuana?  </p>
 
<p>        So Change the Climate proposes to have a public discussion about these issues instead of adding to the disinformation and hysteria that has dominated this issue for decades.  What are politicians and newspapers so afraid of?  Facts like 400,000 tobacco deaths and 150,000 alcohol deaths per year compared to 0 marijuana deaths per year. </p> 
 
<p>        Public debate is the cornerstone of a democracy.  Can Americans handle the truth about marijuana?  I think they already know it.
 </p>
<p>Joseph White<br> 
Executive Director<br>
Change the Climate, Inc.<br>
413.774.4080<br>
<a href="http://www.changetheclimate.org">http://www.changetheclimate.org</a></font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
