
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">

<font face="geneva,verdana,tahoma, sans-serif">
<b>Oakland Club to Argue For Cannabis</b>
</font>
<p>
<font face="geneva,verdana,arial" size="-1">
<b>
by Michelle Locke
<br>
The Associated Press</b><p>

<img src="../images/medical_marijuana.jpg" height="130" width="94" alt="medical marijuana" align="left" hspace="6" vspace="6" border="1">OAKLAND, Calif. (AP) - A few years ago, an author writing about death asked ailing AIDS patient Michael Alcalay how he was accepting dying.
<p>
``I'm not accepting it,'' Alcalay retorted.
<p>
Alcalay is alive today thanks in part, he believes, to doses of marijuana that helped him keep his medicines down and appetite up as he fought the disease.
<p>
On Wednesday, Alcalay will be in the audience as lawyers try to convince the U.S. Supreme Court that federal anti-drug laws shouldn't prevent marijuana from being given to seriously ill patients for pain relief.
<p>
``Once the justices recognize what's really at stake in this case, if any semblance of justice prevails then so will we,'' said Robert Raich, an attorney representing the Oakland Cannabis Buyers' Cooperative.
<p>
The cooperative is a distribution club operating under California's Proposition 215, the voter-approved law that allows the possession and use of marijuana for medical purposes on a doctor's recommendation.
<p>
That's where Alcalay used to get his marijuana. But he's had to look elsewhere since the federal government sued the cooperative and five other California pot clubs in 1998 to prevent them from distributing the drug.
<p>
A federal judge sided with the government. But last year, the 9th U.S. Circuit Court of Appeals ruled that ``medical necessity'' is a legal defense.
<p>
California officials, including Attorney General Bill Lockyer, argue that the state has the right to enforce its medical marijuana law, which was approved by voters in 1996. Distribution clubs sprang up because Proposition 215 is silent on how patients will get marijuana, outside of growing and harvesting it themselves.
<p>
The Supreme Court is not looking directly at Proposition 215, but rather at whether medical necessity may be used as a defense against federal drug bans. It's unclear whether the justices will rule on that general issue or rule more narrowly on how lower courts have handled this case.
<p>
If the court says ``Yes'' to the necessity defense, it could make it easier to distribute medical marijuana in California and the eight other states with similar laws - Alaska, Hawaii, Oregon, Washington, Arizona, Maine, Nevada and Colorado.
<p>
Supreme Court Justice Stephen G. Breyer has recused himself because he is the brother of Charles Breyer, the federal district judge who ordered the club to stop distributing marijuana.
<p>
The club remains open, but only to sell legal hemp products and maintain a membership database.
<p>
Justice Department lawyers declined to comment on the case. They have argued that allowing clubs to hand out marijuana compromises the government's ability to enforce federal drug laws.
<p>
Advocates say marijuana is a reliable and nontoxic therapy that in some cases is the only relief for suffering people.
<p>
That point of view was endorsed recently by the Institute of Medicine. The institute, which was asked to examine the issue by the White House drug policy office, said that because the chemicals in marijuana ease anxiety, stimulate appetite, ease pain and reduce nausea and vomiting, they can be helpful for people undergoing chemotherapy and people with AIDS.
<p>
Institute officials also warned that smoking marijuana can cause respiratory disease and recommended development of forms of the drug that could be taken in other ways.
<p>
Alcalay, a 59-year-old physician who serves as the club's medical director, started using marijuana to keep down his medication after he was diagnosed with HIV in the 1980s. HIV turned into AIDS and in the mid-1990s Alcalay almost died from an intestinal illness that ran roughshod over his weakened immune system.
<p>
Although he lost 35 pounds off his 165-pound, 5-foot-10 frame, he said small doses of marijuana helped make meals palatable. ``I don't like getting stoned. I like to be in control,'' he says.
<p>
He credits marijuana with keeping him alive until the advent of drugs that boosted his immune system and wiped out the intestinal bug.
<p>
Alcalay didn't make it into the book about dying.
<p>
Recently, he ran into the author.
<p>
``He was surprised to see me,'' Alcalay said.<p>
The Oakland Cannabis Coop can be found <a href="http://www.rxcbc.org/" target="_blank">here</a>.
</font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
