
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">

<font face="geneva,verdana,tahoma, sans-serif">
<b>A Nauseating Ruling</b>
<p>
by Dan Shapiro<br>
<a href="http://www.salon.com" target="_blank">Salon.com</a>
</font><p>
<font face="geneva,verdana,arial" size="-1"> 
<img src="../images/cover.jpg" height="343" width="293" alt="Medical Marijuana's Death" align="right" hspace="6" vspace="6">May 15, 2001 | Thirty minutes after my chemo infusions, the surges and swells would start and grow until the whole sky was gray and the waves were capped with a vicious silver. Chemo nausea isn't like any other kind. It's relentless. It's driving. Every flu is packed together into a hurricane. 
<p>
A body that knows it's been poisoned fights back. It's willing to expunge -- by all means necessary -- every ounce of toxin to survive. 
<p>
I learned this the hard way. I tried chemotherapy without weed the first time around, even though a friend who'd had the same chemotherapy said I shouldn't go it alone. "Chemo's grim, man," he muttered into the phone. "Get weed." I tried my chemo regimen without weed. Once. 
<p>
From then on I didn't captain a chemo boat without smoking a pinch of the magic herb immediately after. And it was magic. It steadied the seas on contact. Cleared the sky. From that first pull of smoke through my lungs I was back to a glassy sea, the same glassy sea most people take for granted. 
<p>
I'm sure Clarence Thomas takes it for granted. 
<p>
Through five years of treatment for Hodgkin's disease I relapsed twice, had the maximum dosage of mantle radiation one person should be allowed to enjoy in a lifetime, absorbed 12 chemotherapy agents in a variety of colors and means of infusion, and had surgery nine times. Medications were responsible for rashes, mouth sores, warts, headaches, nausea, vomiting, dry heaves, bone pain, gut pain and shingles. My temperature climbed as high as 106.5 and I had rigors, which are violent, full-body shakes of Victorian proportions. 
<p>
I peed blue from the dyes I drank to go under scanners; once all the hair on one side of my leg stopped growing. The medications made me manic and agitated, depressed and somnolent. I was an insomniac and at other times unable to stay awake. I had a voracious appetite and anorexia. I was unable to think and at other times felt every sensation so vividly, so clearly, that I thought someone had turned up the volume on the world. 
<p>
I had Adryiamycin, Bleomycin, Cytoxan, DTIC, Nitrogen Mustard, Prednisone, Procarbazine, Vincritstine, Vinblastine and VP-16. I've taken percoset, demerol, morphine, ativan, restoril, dalmane and halcion. 
<p>
Oh yeah, and marijuana. 
<p>
Weed was one of the few drugs that offered relief. It didn't knock me out or speed me up, it didn't destroy my heart muscle or take out my hair, it didn't slow my thinking or slur my speech. It didn't attack my bowels or make my fingers numb. 
<p>
It did give me some peace. 
<p>
It did settle my stomach. 
<p>
It did revive my appetite. 
<p>
It did not lead to an addiction. 
<p>
It did not cost a lot of money. (Partly because my mom grew it for me in her backyard.) 
<p>
It worked. 
<p>
Clarence Thomas thinks I'm wrong, or depraved, or faking it. Writing for the court, he said, "In the case of the Controlled Substances Act, the statute reflects a determination that marijuana has no medical benefits worthy of an exception." He noted that the act is based on the assumption that marijuana has "no currently accepted medical use." 
<p>
By that definition, I'm a crazy drug addict. In fact, I'm a doctor. Hell, I'm even a faculty member at a respected medical school. But hey, you don't have to take my word for it. Just up the street from Clarence Thomas' office there's a group of scientists who've taken a careful look at my magic weed. 
<p>
In 1998, under pressure from the public to investigate the medical use of marijuana, the Office of National Drug Control Policy funded a study by the Institute of Medicine, which appointed an independent review panel. The Institute of Medicine asked 11 scientists to review the evidence for the effectiveness of marijuana as a medicine. 
<p>
In the process of preparing a report, the panel used scientific reviews, public hearings and reports from other agencies, and enlisted the assistance of numerous advisors and reviewers. In March 1999 it concluded that marijuana is effective in four circumstances: for reducing nausea and vomiting from chemotherapy, for reducing rapid weight loss from AIDS, for alleviating some types of pain and for treating muscle spasms associated with multiple sclerosis. 
<p>
The Institute of Medicine also found that in 1996 roughly one-third of the U.S. population had tried marijuana but only one-twentieth of the population used it regularly. Of the regular users, very few developed a dependence or abuse problem in which their lives were interrupted by the drug. Few smoked pot after age 34. The study also found that people who do try harder drugs tend to have a co-occurring psychiatric disorder or a family history of psychopathology including alcoholism, and that marijuana usage is not a significant cause of harder drug use. 
<p>
As a doctor, and a cancer patient, I find this information to be extremely relevant, if not crucial. I would have thought that a judge in Mr. Thomas' robes might also find it useful. 
<p>
How about this: A lot of people argue that medical use of marijuana will lead to a perception that marijuana is safe. In the 1920s and 1950s there was a similar concern that physicians' increased prescription of opiates would lead to high rates of addiction. In fact, despite the much greater potential for biological addiction to opiates, there's been no black market swell in opiate use. People still accurately perceive, despite the legal prescription use of opiates, that they are not safe or harmless. 
<p>
In fact, what we do know -- particularly those of us who are doctors -- is that too many people suffer needlessly out of fear of addiction when they need these drugs the most. 
<p>
The folks at the Institute of Medicine have written that "few people begin their drug addiction problems with misuse of drugs that have been prescribed for medical use." A careful look at states and countries that have decriminalized marijuana shows that there is no evidence that such actions lead to increased use. 
<p>
I learned this privately, without benefit of distance or government funding, in that dark little room where I fought the side effects of chemotherapy. 
<p>
May you, Justice Thomas, never have to find out the hard way. 
</font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
