
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">

<font face="geneva,verdana,tahoma, sans-serif">
<b>Government Backs Legalizing Marijuana</b>
</font><p>
<font face="geneva,verdana,arial" size="-1">
<b>Chicago Sun-Times</b><p>

BERNE, SWITZERLAND The Swiss government has endorsed a draft law that would
legalize the consumption of marijuana and hashish and allow a limited
number of "dope shops."
<p>
The bill, submitted to the parliament Friday, seeks to bring Swiss law into
line with the reality that one in four Swiss age 15 to 24 regularly gets
high, according to a poll commissioned last month by the Swiss government.
<p>
"Decriminalizing the consumption of cannabis and the acts leading up to
this takes account of social reality and unburdens police and the courts,"
the government said in a statement.
<p>
The Cabinet agreed in principle in October to legalize dope smoking. It has
now recommended that police be allowed to turn a blind eye to people
growing and trading small amounts of soft drugs, arguing this will make it
easier to differentiate between small- and large-scale dealing.<P align="center">
<font size="-2">Article is &copy; 2001 Chicago Sun-Times.</font></p>
</font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
