
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">
<img src="../images/spacer.gif" height="1" width="500"><br>
<b>
<font face="verdana, geneva, tahoma, arial">Where would you like to see our ads?  Vote Below!</b></font>
<p>

<form ACTION="http://www.mypoll.net/cgi-bin/vote" METHOD="POST" target="_blank">
<input type="hidden" name="id" value="25656">
<font face="verdana, geneva, tahoma, arial" size="-1"><b>Which city would you like to see our ads in?</b></font><br><br>
<font face="verdana, geneva, tahoma, arial" size="-1">
<input type="radio" name="vote" value="1">Memphis<br><input type="radio" name="vote" value="2">Miami<br><input type="radio" name="vote" value="3">San Jose<br><input type="radio" name="vote" value="4">Milwaukee<br>
</font><br><br>
<input type="submit" value="Submit Vote" name="submit"><br><font face="verdana, geneva, tahoma, arial" size="-2">
<a href="http://www.mypoll.net/cgi-bin/vote?id=25656" target="_blank">Current Results</a></font>
</form>


</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
