
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">

<font face="geneva,verdana,tahoma, sans-serif">
<b>Whitney Houston's Drug Case Dropped</b>
</font><p>
<font face="geneva,verdana,arial" size="-1">
<b>The Associated Press<br>
Mar 8 2001 2:25PM</b><p>

HILO, Hawaii (AP) - A judge has dismissed a marijuana possession charge against singer Whitney Houston, leaving her with a clean record in Hawaii, prosecutors said. 
District Judge Joseph Florendo Jr. dismissed the petty misdemeanor marijuana possession charge Monday after a substance abuse assessment was filed on her behalf, said Deputy Prosecutor Melvin Fujino. 
<p>
The assessment, submitted on Feb. 22 by Michael Burke, a certified substance abuse counselor in Highland Park, N. J., stated Houston doesn't require treatment for substance abuse. 
<p>
Houston's bag was seized at the Keahole-Kona Airport on Jan. 11, 2000. Fujino and Houston's attorneys stipulated in court in November that the bag contained less than half an ounce of marijuana in two plastic baggies and three partially smoked marijuana cigarettes. 
<p>
The 37-year-old singer, who was not arrested, allegedly abandoned the bag and boarded a United Airlines flight for San Francisco with her husband, singer Bobby Brown, before police arrived. 
</font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
