#!/usr/bin/env python

# sudo pip install gmusicapi

from gmusicapi import Mobileclient

client = Mobileclient()

logged_in = client.login( 'will@dhappy.org', '' )

print logged_in

for playlist in client.get_all_playlists():
    print playlist
