#!/bin/bash

cd ...
git add -n .

ACTION=
SEC=5
while [ $SEC -gt 0 ]; do
    read -p $'\015'"${SEC}s: Add? [? Yn] " -t 1 -n 1 ACTION
    [ $? -eq 0 ] && SEC=0
    SEC=$(( $SEC - 1 ))
done

case "$ACTION" in
    [\?] ) echo $'\012'"?";;
    [ ] ) break;;
esac

git add -n .
