CC=javac
CCFLAGS=
OBJ:\
	CommandInterpreter.class arm.class Register.class base.class point.class vect.class joint.class program.class Claw.class robot.class

CommandInterpreter.class: CommandInterpreter.java
	$(CC) $(CCFLAGS) CommandInterpreter.java

arm.class: arm.java
	$(CC) $(CCFLAGS) arm.java

Register.class: Register.java
	$(CC) $(CCFLAGS) Register.java

base.class: base.java
	$(CC) $(CCFLAGS) base.java

point.class: point.java
	$(CC) $(CCFLAGS) point.java

vect.class: vect.java
	$(CC) $(CCFLAGS) vect.java

program.class: program.java
	$(CC) $(CCFLAGS) program.java

joint.class: joint.java
	$(CC) $(CCFLAGS) joint.java

robot.class: robot.java
	$(CC) $(CCFLAGS) robot.java

Claw.class: Claw.java
	$(CC) $(CCFLAGS) Claw.java
