#!/bin/bash

OUTDIR=breakout

[ -e "${OUTDIR}" ] || mkdir "${OUTDIR}"
/usr/bin/xsltproc --stringparam outdir "${OUTDIR}" xslt svg
for file in "$OUTDIR/"*; do
    NAME=$(xpath -e "/*/*/@inkscape:label" -q "$file" | sed -e s/^[^'"']*'"'\\\([^'"']*\\\)'"'/\\1/)
    if [ ! -z "${NAME}" ]; then
        echo "Linking: ${OUTDIR}/${NAME}"
        mkdir --parents "${OUTDIR}/${NAME}"
        ln -s "$(echo $NAME | sed -e 's|[^/]*|..|g')/${file##*/}" "${OUTDIR}/${NAME}/svg"
    fi
done

