
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("http://www.changetheclimate.org/header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">

<font face="geneva,verdana,tahoma, sans-serif">
<b>Article Title</b>
<p>
Author<br>
<a href="#" target="_blank">Source</a>
</font><p>
<font face="geneva,verdana,arial" size="-1"> 
Article
</font>
</td>
<td valign="top" align="right">
<? include ("http://www.changetheclimate.org/right.phtml"); ?>
</body>
</html>
