
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">
<img src="../images/dn_logo.gif" width="112" height="66" alt="New York Daily News"><p>
<b>
<font face="verdana, geneva, tahoma, arial">Pro-Pot Ads Rolling Into City</b></font>
<p>

<font face="verdana, geneva, tahoma, arial" size="-1">
By Peter DeMarco<br> 
Daily News Express<p>

Pro-pot ads banned in Boston and put up in Washington only after threats by First Amendment lawyers may be coming to a subway or bus stop near you - assuming Mayor Giuliani doesn't snuff them out.<p>

The marijuana advocacy group Change the Climate launched its controversial ad campaign last week in the nation's capital.
<p>
The ads don't encourage people to smoke and its use as a medicine.
<p>
One ad features a picture of a well-dressed businesswoman quoted saying, "I've got three great kids. I love them more than anything. I don't want them to smoke pot. But I know jail is a lot more dangerous than smoking pot."
<p>
Just how high the Giuliani administration will be on the ads remains to be seen. City Hall had no immediate response.
<p>
"I'm not sure what to expect," said Joseph White of Change the Climate, which plans to buy ad space here. "From what little I know of the mayor's reputation, it wouldn't surprise me if he [opposed] our public information campaign."
<p>
Metropolitan Transportation Authority spokesman Tom Kelly said any pro-pot ad would need to be reviewed by attorneys.
<p>
"There are all different forms of measuring sticks, depending on the ad," he said. "But we do not promote illegal activities."
<p>
Massachusetts Gov. Paul Cellucci rejected the ads for Boston, saying they promote drug use. The matter is now in the courts.
<p>
Washington's Metro subway line accepted the ads only after the American Civil Liberties Union threatened a lawsuit.</font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
