<? 
$page_title = "Marijuana Prohibition Wastes Taxes ";
$relpath = "../../";
include ($relpath . "top.php");
?><font face="verdana, geneva, tahoma, arial"> </font> 
<p><font face="Verdana, Geneva, Tahoma, Arial" size="+1"><b>Marijuana Prohibition 
  Wastes Taxes</b></font> <br>
<table width="443" border="0" cellspacing="2" cellpadding="0" align="center">
  <tr>
    <td valign="top" align="center"><b><font face="Verdana, Geneva, Tahoma, Arial"><a href="bus_card.pdf"><img src="../../images/pdf-icon.gif" width="32" height="32" align="absmiddle" border="0" hspace="3"></a><a href="bus_card.pdf">Download 
      and print this ad now!</a></font></b> <font face="Verdana, Geneva, Tahoma, Arial" size="-1">(PDF, 
      303k)</font> <br>
      <a href="http://www.cafeshops.com/ctconline.7613638"><img src="../../images/bumpersticker.jpg" width="156" height="51" border="0" alt="Get the Bumper Sticker!"><br>
      <font face="Verdana, Geneva, Tahoma, Arial"><b>Get the Bumper Sticker!</b></font></a></td>
  </tr>
</table>
<p><font face="Verdana, Geneva, Tahoma, Arial" size="-1"><img src="../../images/save-our-taxes-web-ready.jpg" width="433" height="155" align="right" alt="Save our Taxes!  Legalize and Tax Marijuana.">It 
  is common knowledge that U.S. taxpayers pay billions of dollars each year to 
  fund the failed War on Drugs. A simple analysis of the War on Drugs shows that 
  most of the costs borne by taxpayers are for marijuana prohibition. With over 
  700,000 annual arrests, thousands of prisoners and hundreds of millions of dollars 
  spent on anti-marijuana television ads, the War on Drugs is mostly a War on 
  Marijuana.</font></p>
<p><font face="Verdana, Geneva, Tahoma, Arial" size="-1">You can view several 
  reports on the waste of taxpayer dollars and how much one state - Massachusetts 
  - would save in taxes if marijuana was regulated and made available through 
  legal distribution similar to how alcohol is regulated.</font></p>
<p><font face="Verdana, Geneva, Tahoma, Arial"><a href="/news/arrest_costs.php"><b>Marijuana 
  prohibition costs taxpayers at least $7 billion annually</b></a></font></p>
<p><font face="Verdana, Geneva, Tahoma, Arial" size="-1"><b>With $7 billion U.S. 
  taxpayers could . . .</b></font></p>
<ul>
  <li><font face="Verdana, Geneva, Tahoma, Arial" size="-1">Give every public 
    school teacher a raise of over $2,000.</font></li>
  <li><font face="Verdana, Geneva, Tahoma, Arial" size="-1">Increase the public 
    education budget by about 2%.</font></li>
  <li><font face="Verdana, Geneva, Tahoma, Arial" size="-1">Provide health insurance 
    to 15 million uninsured Americans, over 30% of our 43 million fellow uninsured 
    Americans, many of who are children.</font></li>
  <li><font face="Verdana, Geneva, Tahoma, Arial" size="-1">Serve school lunches 
    to more than 25 million underprivileged children.</font></li>
</ul>
<p><font face="Verdana, Geneva, Tahoma, Arial"><b>Boston University Study Shows 
  $138 million in New Revenue if Massachusetts Legalizes Marijuana.</b></font></p>
<p><font face="Verdana, Geneva, Tahoma, Arial" size="-1">You can <a href="/bu-study/">read 
  the report that Change the Climate commissioned here</a>. The study was conducted 
  by Professor Jeffery Miron, Department of Economics, Boston University.</font></p>
<p><font face="Verdana, Geneva, Tahoma, Arial" size="-1">In short, the groundbreaking 
  study shows that the Commonwealth of Massachusetts would have $138 million more 
  revenue if marijuana was regulated and taxed. Most of the new revenue comes 
  from taxpayer savings that are now spent on arresting, administering, prosecuting 
  and jailing marijuana offenders. Millions more would be generated by taxes on 
  the legal sales of marijuana. </font></p>
<p><font face="Verdana, Geneva, Tahoma, Arial" size="-1">Of course Massachusetts 
  cannot legalize marijuana until the federal government changes its policies 
  to allow states to administer their own laws governing marijuana. </font><br>
</p>
<p><font face="Verdana, Geneva, Tahoma, Arial" size="-1">If you know of other 
  studies or information on how marijuana laws waste taxpayer dollars, please 
  send the information or link to <a href="mailto:info@changetheclimate.org">info@changetheclimate.org</a>.</font></p>

  <? include ($relpath . "right.php"); ?>
