
<html>
<head><title>Change the Climate - An educational site about marijuana and the war on drugs</title>
<? include ("../header.phtml"); ?>
<table border="0" cellPadding="6" cellSpacing="0" width="690" align="center">
<tr>
<td valign="top">
<img src="../images/wallstreetlogo.gif" height="145" width="144" alt="Wall Street Journal" border="0"><p>
<font face="geneva,verdana,tahoma, sans-serif">
<b>Tougher Bush Stance On Obscure Law Hits Students Seeking Financial Aid</b></font><p>

<font face="geneva,verdana,tahoma, sans-serif" size="-1">Any Drug Conviction Bars Applicants From Getting Federal College Funds
</font>

<p>
<font face="geneva,verdana,arial" size="-1">
by Daniel Golden
<br>
The Wall Street Journal<p>

Last year, Kristopher Sperry, a young man with a longtime marijuana habit,
 decided to clean up his life. He got married, became a father, joined a
 Baptist church and enrolled as a freshman at Arkansas State University. He
 earned a "B" average and maintained a spotless disciplinary record.
<p>
 But this semester, the 23-year-old former factory worker lost his
financial aid and had to drop out of school because he couldn't afford the $600
 tuition. The reason: He had two misdemeanor drug convictions, one in 1998
 for marijuana possession and one in 1999 for possession of drug
 paraphernalia, namely a water pipe. Under a three-year-old law, that makes
 him ineligible for federal student aid.
<p>
 "Arsonists, burglars and convicted felons can still qualify for aid,"
 complains Mr. Sperry, who had his driver's license temporarily revoked,
 paid $275 in fines and performed a day of community service as a result of
 the convictions. "I've already paid my price for my crime, I believe. Now
 I'm having to pay an even more severe price, hindering my education."
<p>
<b>From Pot to Heroin</b>
<p>
 The law Mr. Sperry ran afoul of passed with scant debate in 1998 as part
of a massive bill reauthorizing all federal spending on postsecondary
 education. It denies federal student financial aid to anyone convicted of
a drug crime, whether smoking marijuana or trafficking heroin. The length of
 ineligibility varies according to the gravity of the offense and the
number of convictions. A single conviction of Marijuana possession, by far the
 most common drug charge, disqualifies a student for a year from the date
of conviction. People convicted of crimes that don't involve drugs, no matter
 how serious, are eligible for student aid.
<p>
 The law has been little noticed until recently because the Clinton
 administration enforced it only very loosely. But the new Bush
 administration has decided to get strict.
<p>
 Consequently, some 26,000 people appear ineligible for federal financial
 aid for the upcoming school year with a little more than a third of the
 expected applications in hand. Supporters of the law call it an important
 step in fighting drugs, arguing it will force many student drug users to
 change their behavior for fear of losing aid. But opponents warn that the
 law deters many drug offenders from applying to educational programs and
 deprives them of an opportunity to remake their lives.
<p>
 Confusion has surrounded the implementation of the law from the start.
 Officials from both the Clinton and Bush administrations say the
difference in enforcement stems not from a divergence in philosophy but rather
 uncertainty about how to police the law. In an effort to comply with it,
 the Clinton Education Department in 1999 added a new question to the
 federal financial aid application for the 2000-2001 academic year, asking
 about drug convictions. Of the 9.8 million applicants, only about 9,000
 acknowledged having a drug record on the form. As a result, they were
 denied aid.
<p>
 But 279,000 more applicants left the question blank. After heated internal
 debate, the Education Department decided to award aid to all of those
 people, contending that a blank probably meant "No" because the question
 was poorly worded.
<p>
<b>Fixing the Question</b>
<p>
 Realizing they had a problem, Clinton officials tested the question on
 student focus groups and concluded they needed to rewrite it. The revised
 question on the form for the 2001-2002 school year reads: "Do not leave
 this question blank. Have you ever been convicted of possessing or selling
 illegal drugs?"
<p>
 Then the Bush administration took over. Last month Education Secretary Rod
 Paige, after consulting with the department's legal counsel, decided that
 the wording was now so clear that the government should deny aid to anyone
 who left it blank.
<p>
 "We arrived at a practice we felt reflected the intent of Congress," says
 Lindsay Kozberg, an Education Department spokeswoman. She declined to
 comment further about the internal deliberations.
<p>
 This year, as of April 8, about 11,000 students out of 3.9 million
 applicants have left the question blank, and more than 15,000 have been
 declared ineligible by admitting to a drug conviction. The Education
 Department is still reviewing many of these cases.
<p>
 Student groups and administrators at many campuses have opposed the law
 since its inception, but now their protest is rising. Student governments
 at 59 colleges, as well as a national association of college financial aid
 officers, have endorsed a repeal bill sponsored by U.S. Rep. Barney Frank,
 a Massachusetts Democrat. But the bill, which failed last year, stands
 little chance of passing a Republican Congress since many lawmakers are
 reluctant to look soft on drugs.
<p>
 Still, U.S. Rep. Mark Souder, an Indiana Republican who sponsored the bill
 that led to the law, is pushing to scale it back. He says he never
intended it to apply to applicants with prior convictions -- only to students
 convicted of a drug offense while they were receiving federal aid.
<p>
 "The last thing I want to do is reach back and punish" applicants with
 prior records, Rep. Souder says. "That's like saying, 'Once a criminal,
 always a criminal.'"
<p>
 But supporters of the law, like Robert Maginnis, vice president of the
 Family Research Council, a conservative Washington think tank, argue that
 the limited pool of federal financial aid funds -- totalling $48 billion
in grants and loans -- should be reserved for law-abiding students. "It's a
 privilege to receive financial aid. If you want taxpayer money, you have
to abide by the rules, which includes staying drug-free," says Mr. Maginnis.
 He favors restricting financial aid for other criminals as well, but says
 it's particularly crucial to deny assistance to drug offenders, contending
 that abuse of drugs underlies at least half of all crime in the U.S. yet
 universities take the issue lightly.
<p>
 In college newspapers, campus activists have portrayed the law as an
attack on otherwise upstanding college students who use marijuana recreationally.
 There is also another segment of affected applicants: hard-core substance
 abusers or dealers, many of them minorities, who are seeking to redeem
 themselves through education. For these offenders, mainly looking to
attend community colleges and trade schools, the ban reinforces other roadblocks
 they encounter in housing and employment.
<p>
 "If you can't get education or housing or certain types of jobs, you hang
 with people who have a similar kind of restricted life," says Phillip
Clay, a professor of urban planning at the Massachusetts Institute of
Technology. "It's stupid to have a law that says you can rob a bank, serve five years,
 and live happily ever after, but if you're caught with a joint or a vial
of some stronger drug you're barred from the benefits of society, especially
 those that can reduce recidivism."
<p>
 At the Hampden County Correctional Center in Ludlow, Mass., there are nine
 students in Prof. James Carvallo's English composition class, including
two child molesters, a thief, and several people convicted of assault. Another
 inmate, Timothy Grant, is eager to join the class, which is offered under
a program run by nearby Springfield Technical Community College. His
 high-school equivalency degree satisfies the admission standards, and
 prison staffers say he is a prime candidate for rehabilitation via
education.
<p>
 But Mr. Grant is serving time for dealing crack, so he can't enroll
because he can't get the federal financial assistance he needs to pay the $247
 tuition. Most of the other students in the class are receiving federal
aid.
<p>
 Mr. Grant, 26 years old, is serving a two-year sentence. He says he has
 been dealing crack on street corners in the nearby city of Springfield
 since he was 14. He's been arrested twice before. In a previous
 incarceration at the prison from 1995 to 1997, before the law was passed,
 Mr. Grant earned his equivalency degree and received financial aid to take
 community-college courses. His grades were average.
<p>
 After his release, he moved to his native Alabama and worked as a welder.
 He stayed two years -- until a cousin visiting from Massachusetts
persuaded him to come back and sell crack again. "I was feeling stressed living
 paycheck to paycheck," he says. "It was kind of hard." Six weeks later, he
 was arrested again.
<p>
 Since he has been convicted three times of dealing, Mr. Grant faces a
 lifetime ban on federal aid. But offenders can restore eligibility by
 completing a treatment program and passing random drug tests. So Mr.
Grant, who insists that even though he sold crack he never used the drug himself,
 is nonetheless participating in drug treatment at the prison so he can
 qualify for financial aid. The prison program is free to him, but
offenders who have already served time often find outside treatment programs
 expensive and hard to get into because they have long waiting lists.
<p>
 Assuming he finishes the treatment program, Mr. Grant says he intends to
 pursue his college studies in prison and after his release next year. With
 a degree, he says, he could find a decent job, make his two children proud
 and avoid the fate of other dealers he knows who were killed. "I want to
do something with my life and be something besides a wannabe gangster," he
says.
<p>
 Though the classes he took during his previous prison term didn't keep him
 from returning to jail, a prison official insists that education could yet
 be Mr. Grant's salvation. "I hold out more hope that he'll make it the
next time. It can take a few times," says Lisa Ouimet Burke, the prison's
 education coordinator. A recent study by Ms. Burke found that inmates who
 took college courses in the Hampden prison were half as likely to return
 within three years of release as were other inmates with high-school
diplomas.
<p>
 Kristopher Sperry also tried to restore his eligibility by enrolling in a
 treatment program. After Arkansas State determined that his two
convictions disqualified him for aid until this fall, he dropped out and took a job
 washing cars. He made an appointment to check into a state-funded drug
 treatment clinic nearby.
<p>
 But when he told his manager that he needed a month's leave for drug
 treatment, the boss fired him, saying the company couldn't afford to hold
 his job open. Discouraged, Mr. Sperry skipped the treatment program. "I
was afraid, if I did go to rehab, I would miss my little girl's first steps,"
 he says. He says he now smokes marijuana only occasionally and hopes his
 newfound religious faith will help him finally beat the habit.
<p>
 This month, Mr. Sperry and two others were arrested as a result of a
 long-running undercover operation by the local sheriff's office and
charged with selling one ounce of marijuana for $170. The alleged crime took place
 in February 2000, before his marriage and efforts to reform. If convicted,
 Mr. Sperry would lose financial aid indefinitely. Mr. Sperry said he
 intends to plead innocent.
<p>
 The financial-aid ban is one of several federal measures enacted during
the past decade restricting drug offenders' access to government benefits. A
 1992 law prodded states -- on penalty of losing highway-construction funds
 -- to pass legislation revoking drivers' licenses of drug offenders for a
 minimum of six months. Seventeen of them did. A 1996 federal law prohibits
 people convicted of drug felonies from ever receiving welfare or food
 stamps. Since then, 27 states have modified or eliminated that ban.
<p>
 Other federal legislation bars drug offenders from subsidized or public
 housing for at least three years. Some local housing authorities have
 extended that waiting period to five years.
<p>
 In 1994, Congress eliminated the federal government's main student grant
 program, Pell grants, for inmates in state and federal prisons, ending
 higher education in most of those facilities. Ms. Burke, the Hampden
County prison's education coordinator, says that at least half a dozen inmates
 there have declined transfers to lower-security state facilities so they
 can keep taking college courses at the county jail.
<p>
 Drug offenders who lie on the financial-aid form usually qualify for aid
 because neither the government nor universities seek to verify responses.
 "The Al Capone of drug dealers could answer no, and there are no checks,"
 says David Allen, financial-aid director at Bristol Community College in
 Fall River, Mass. Ms. Kozberg, the Education Department spokeswoman, says
 the government checks answers to all questions on a sample of applications
 but doesn't pay special attention to the drug responses.
<p>
 Some college and university officials believe that the law will have
little impact on campus drug use. That's because colleges often prefer to handle
 drug offenses in-house rather than turn them over to local law-enforcement
 authorities. More than one-third of college students report using
marijuana within the past year, according to surveys. Yet, of more than 1.5 million
 drug arrests in 1999, only 10,482 occurred on college campuses. Nearly
 twice as many on-campus drug violations -- 18,466 -- were referred to
 university disciplinary boards.
<p>
 In fact, the financial-aid ban could reduce campus arrests, since colleges
 may be reluctant to forfeit the federally funded tuition payments. Some
 off-campus law enforcement officials also appear sympathetic to students'
 plight. In January, Dylan Rood, a 20-year-old junior at Wesleyan
University in Middletown, Conn., was charged in his hometown of Sierra Madre, Calif.,
 with possessing less than an ounce of marijuana. Mr. Rood, a geology major
 with a B-plus average and no prior record, told police and prosecutors
that he would have to quit school if convicted because he would lose his
student loans.
<p>
 They agreed to drop the drug charge and let him plead guilty to disturbing
 the peace. He paid a $135 fine but preserved his financial aid.
 </p>
</font>
</td>
<td valign="top" align="right">
<? include ("../right.phtml"); ?>
</body>
</html>
