#!/bin/bash

pushd dirname($0)
PROG="svnadmin"
DIR="date/$(date --utc +'%Y/%b/%d/@%Ih%M')/$PROG"
mkdir --parents --verbose "$DIR"
SRC="/home/wjholcomb/svn/sites/"
[ -e "$DIR" ] && $PROG dump $SRC > "$DIR/dump"
