run:
	../appengine/google_appengine-py/dev_appserver.py .

runclean:
	../appengine/google_appengine-py/dev_appserver.py --clear_datastore .


deploy:
	../appengine/google_appengine-py/appcfg.py update .
