#!/bin/bash

# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for a sample

#GIT_WORK_TREE=~/tip/book/ git checkout

CURRENT="$(pwd)"
HOME="$(echo ~)"
LOCAL="${CURRENT#${HOME}/}"
LIB="repo"
ROOT="${LOCAL#${LIB}/}"
TYPE="git"
PATH="${ROOT%/${TYPE}}"

pushd ~/"$PATH"
/usr/bin/env -i git pull origin master
/usr/bin/env -i git remote | grep -q '^github$' && git push github master 
/usr/bin/env -i git update-server-info
