#!/bin/bash

# If running interactively, then:

if [ "$PS1" ]; then
    PS1='\u@\h\[\033[1;35m\]:\[\033[0m\]\w\[\033[1;33m\]\$\[\033[0m\] '
fi

# if on the accre cluster, log into the head
if [[ "${HOSTNAME#*.}" == "vampire" && "${HOSTNAME%.*}" != "vmpsched" ]]; then
    ssh vmpsched
    logout
fi

# Mistype: 8/12/2009
alias edit=emacs

export EDITOR="emacs -nw"
export RSYNC_RSH=ssh
export CVS_RSH=ssh
[ -d ~/bin ] && export PATH=~/bin:$PATH
[ -d ~/bin/sdcc/bin/ ] && export PATH=$PATH:~/bin/sdcc/bin/
export FOP_HOME=$(echo ~/bureau_home/fop-0.20.5)

export LANG="en_US.UTF-8"
export LC_ALL=$LANG

# ToDo: make sorting workflow easier by greying out windows quickly
#function setactive() { termcolor('black'); }
#function inactive() { termcolor('grey'); }
#function termcolor() {}

# To remove language selection menus from windows in Solaris
export XIM="htt"
export GTK_IM_MODULE=iiim
export XMODIFIERS="@im=${XIM}"

# Make bash append rather than overwrite the history on disk
shopt -s histappend

# Replace cd with p (pushd) and d (pushd^-1)
# Put in Himinbiorg/shell
alias p=pushd
alias d=popd
alias r=rm
alias l=ls
alias v=start
alias e=emacs

# Not set by OSX'S X server
#[ -z "$DISPLAY" ] && export DISPLAY=":0"

[ -z "$PS1" ] || (which fortune > /dev/null 2>&1 && fortune)

# Include OSX specific pathes; and give them precedence
for path in /usr/local/bin /opt/local/bin /opt/sfw/bin /sw/bin /usr/local/mysql/bin /usr/X11R6/bin; do
    [ -d "$path" ] && export PATH="$path:$PATH"
done

# For invoking the correct handler for files from the command line
which xdg-open > /dev/null 2> /dev/null && alias start=xdg-open

# Command for php5 on dreamhost
DHPHP5=/usr/local/dh/cgi-system/php5.cgi
[ -x $DHPHP5 ] && alias php5=$DHPHP5

MATLAB=/gpfs0/local/x86_64/matlab/2007b/opteron/sysgcc/nonet/bin/matlab_program
[ -e "$MATLAB" ] && alias matlab="sh /gpfs0/local/x86_64/matlab/2007b/opteron/sysgcc/nonet/bin/matlab_program"

# In OSX, mplayer installs to the home directory
# That 'which' doesn't return false in OSX when the program isn't present is dumb
function mplayer() {
    if [ -z "$MPLAYERCMD" ]; then
        if [ -e /usr/bin/mplayer ]; then
            MPLAYERCMD=/usr/bin/mplayer
        else
            MPLAYERCMD="$(find ~ -name mplayer | head -n1)"
        fi
    fi
    if [ "$0" == "-2ndaudio" ]; then
        shift
        MPLAYERARGS="-ao alsa:device=hw=1,0"
    fi
    "$MPLAYERCMD" $MPLAYERARGS "$@"
}

# OSX terminal emulators have trouble with the delete key on the command line
# stty erase 

# Ubuntu maps these keys properly to the XFree86 commands

if [ ! -e /etc/debian_version ]; then
  USBDEVICES=/proc/bus/usb/devices
  [ -e $USBDEVICES ] && grep --silent "Ergonomic Keyboard 4000" $USBDEVICES && {
    xmodmap -e 'keycode 162=F22' 2> /dev/null; # Play/Pause key on Microsoft's Natural Keyboard
    xmodmap -e 'keycode 234=F20' 2> /dev/null; # Back key on Microsoft's Natural Keyboard
    xmodmap -e 'keycode 233=F21' 2> /dev/null; # Forward key on Microsoft's Natural Keyboard
    xmodmap -e 'keycode 176=F19' 2> /dev/null; # Volume increase key on Microsoft's Natural Keyboard
    xmodmap -e 'keycode 174=F18' 2> /dev/null; # Volume decrease key on Microsoft's Natural Keyboard
    xmodmap -e 'keycode 160=F18' 2> /dev/null; # Mute key on Microsoft's Natural Keyboard
  }
fi

BATIK_DIR=~/"Local Applications/batik-1.6/"
[ ! -e "$BATIK_DIR" ] && BATIK_DIR=~/bin/batik-1.6
if [ -e "$BATIK_DIR/batik-rasterizer.jar" ]; then
  function batik-rasterizer() {
    java -jar "$BATIK_DIR/batik-rasterizer.jar" "$@"
  }
fi

# Allow override use of sun's jdk
for JDK in /usr/lib/kaffe/bin/ /usr/java/jdk*/bin/ /usr/lib/j2sdk*/bin/ "/cygdrive/c/Program Files/Java/jdk"*/bin/; do
    if [[ -e "${JDK}java" || -e "${JDK}java.exe" ]]; then
        export PATH="$JDK:$PATH"
        break
    fi
done
export JAVACMD=$(which java)
export JAVA_HOME=${JAVACMD%/*/*}

alias pauseamarok="dcop --user $USER amarok player playPause"

# Allows cutting and pasting from the command line
# Usage: echo "test" | klip
#        klip "test"
#        klip # displays the clipboard's contents
function klip() {
    ps ax | sed 's/^ *[^ ]\+ \+[^ ]\+ \+[^ ]\+ \+[^ ]\+ \+//' | grep -qe '^klipper' || klipper
    if [[ $# -eq 0 ]]; then
        # I don't know how to do nonblocking IO
        (
            read -t1 LINE;
            if [ ! -z "$LINE" ]; then
                dcop klipper klipper setClipboardContents "$LINE$(cat)"
            else
                dcop klipper klipper getClipboardContents
            fi
        )
    else
        dcop klipper klipper setClipboardContents "$*"
    fi
}

# Power down the monitor and unpause Amarok for exiting music on a blog post
function timeblog() {
    TIME=${1:-60} # Number of seconds to wait
    sleep 1 && xset dpms force off && sleep $TIME && qdbus org.kde.amarok /Player org.freedesktop.MediaPlayer.Play
}

function xscreensaver-disable() {
    xscreensaver-command -restart
}

function settitle() {
    echo -n $'\033']0\;$@$'\007'
}

function mp3reencode() {
    newfile="${1%mp3}new.mp3";
    lame --mp3input --preset standard "$1" "$newfile" && (du -h "$1" "$newfile"; mv -i "$newfile" "$1");
}

function mp3oggify() {
    artist=${1% - *};
    track=${1#* - };
    newfile="${1%mp3}ogg";
    lame --mp3input --decode --silent "$1" - | oggenc -o "$newfile" -a "$artist" -t "$track" - && (du -h "$1" "$newfile");
}

function wmaoggify() {
    artist=${1% - *};
    track=${1#* - };
    newfile="${1%wma}ogg";
    mplayer -ao pcm -ao pcm:file="$newfile.temp" "$1";
    oggenc -o "$newfile" -a "$artist" -t "$track" "$newfile.temp" && (du -h "$1" "$newfile");
    rm -fv "$newfile.temp"
}

function reencode() {
    BASENAME="${1%%.*}"
    [ -e "$BASENAME.mkv" ] && { echo "$BASENAME.mkv already exists"; return 1; }

    # mencoder is missing the -x264encopts option so I'm dumping the
    # sources to files and reencoding, not idea, but I'm clueless
    
    if [ ! -e "$BASENAME.h264.mkv" ]; then
        # the framerate has to be set on active streaming files
    
        mplayer -ao null -fps 25 -fixed-vo -noframedrop -vo yuv4mpeg -vo yuv4mpeg:file="$BASENAME.tmp.y4m" $*
    
        # from: http://odin.himinbi.org/Makefile.Coupling

        ENCOPTS="--progress --subme 7 --analyse all --me umh --8x8dct"
        ENCOPTS="$ENCOPTS --qp 23 --min-keyint 12 --keyint 125 --bime"
        ENCOPTS="$ENCOPTS --direct auto --filter 1:1 --ref 16 --mixed-refs"
        ENCOPTS="$ENCOPTS --bframes 5 --b-pyramid --weightb --b-rdo"
        ENCOPTS="$ENCOPTS --trellis 2 --cqm jvt"

        eval x264 -o "$BASENAME.h264.mkv" $ENCOPTS --fps 21.78927 --pass 1 --stats "$BASENAME.x264.stats" "$BASENAME.tmp.y4m"
        eval x264 -o "$BASENAME.h264.mkv" $ENCOPTS --fps 21.78927 --pass 2 --stats "$BASENAME.x264.stats" "$BASENAME.tmp.y4m"
    fi

    if [ ! -e "$BASENAME.tmp.ogg" ]; then
        COUNT=0
        for file in "$@"; do
            COUNT=$(( COUNT + 1 ))
            mplayer -ao pcm -ao pcm:nowaveheader -ao pcm:file="$BASENAME.tmp.$COUNT.wav" -vo null "$file"
        done
        sox "$BASENAME".tmp.*.wav -t wav "$BASENAME.tmp.wav"
        oggenc -o "$BASENAME.tmp.ogg" "$BASENAME.tmp.wav"
        rm -f "$BASENAME".tmp*.wav
    fi

    mkvmerge -o "$BASENAME.mkv" "$BASENAME.h264.mkv" "$BASENAME.tmp.ogg"
}

function playmp3s() {
    file=$(date "+/tmp/%Y_%m_%d.m3u");
    if [ ! -e $file ]; then
        dirs=$(echo /mnt/media/ ~/.mldonkey/incoming/ /usr/share/music/)
        # [ -e "${dirs%* }" ] || dirs=$(echo ~/)
        echo "Finding media in $dirs"
        find $dirs \( -name \*.mp3 -or -name \*.ogg -or -name \*.wma -or -name \*.m4a \) \
            -size +1k -printf "%p\n" > $file;
    fi
    settitle Music
    mplayer -shuffle -playlist $file;
}

export WEBSITE_DIR=~/sites

[ -r "$WEBSITE_DIR/himinbi.org/odin/config/inputrc" ] && export INPUTRC="$WEBSITE_DIR/himinbi.org/odin/config/inputrc"

XSLTTRANS="$WEBSITE_DIR/himinbi.org/odin/jars/XSLTTransformer.jar"
[ -r "$XSLTTRANS" ] && which xsltproc > /dev/null 2>&1 || alias xsltproc="java -jar $XSLTTRANS"

alias c="ssh wjholcomb@himinbi.org"
alias cs="ssh will@stderr.org"
alias ch="ssh will@honors.tntech.edu"
alias ch="ssh will@ebene.madstones.com"
alias ch="ssh will@ebene.dynalias.net"
alias cmad="ssh wholcomb@madstones.com"
alias csf="ssh -t wjholcomb,ideapool@shell.sourceforge.net create"
alias cc="ssh holcomwj@vmplogin.accre.vanderbilt.edu"
alias clab="ssh holcomwj@hmtcomp-7.vuse.vanderbilt.edu"

alias monitorsleep="sleep 1 && xset dpms force off"
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
if [ "${BASH_VERSINFO[5]/apple/}" != "${BASH_VERSINFO[5]}" ]; then # in OSX
    alias dir="ls -G"
    alias flushdns="lookupd -flushcache"
    tset -i
elif [ "${BASH_VERSINFO[5]/solaris/}" != "${BASH_VERSINFO[5]}" ]; then # in solaris
    alias ls=dir
elif [ "${BASH_VERSINFO[5]/cygwin/}" != "${BASH_VERSINFO[5]}" ]; then # in windows
    KEY=CurrentInstallFolder
    WINDOWSSDK=$(reg query "HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows" /v $KEY | grep $KEY | sed -e 's/.*REG_SZ[[:space:]]*//')
    WINDOWSSDK=$(cygpath -p "$WINDOWSSDK\bin")
    [ -e "$WINDOWSSDK" ] && PATH="$PATH:$WINDOWSSDK"

    # this fixes a problem with emacs not exiting properly
    # it will cause the terminal to break though if it is set here rather than in the global env
    [ -z "$CYGWIN" ] && export CYGWIN=tty

    # mingw's compiler needs to be used before cwywin's to compile QT stuff
    mingwdir="/cygdrive/c/Documents and Settings/$USERNAME/My Documents/Programs/mingw32/bin/"
    [ -d "$mingwdir" ] && export PATH="$mingwdir:$PATH"

    # to use the python image library, use the windows binary
    pythondir=$(echo "/cygdrive/c/Program Files/"[Pp]ython*)
    [ -d "$pythondir" ] && PATH="$pythondir:$PATH"

    # Include pathes for QT under Windows
    # QT's make system relies on make being called from QT rather than cygwin
    # export QTDIR=$(echo "/cygdrive/c/Documents and Settings/$USERNAME/My Documents/Programs/QT/"*)
    export QTDIR=$(echo "/cygdrive/c/Qt/"*)
    [ -d "$QTDIR" ] && export PATH="$QTDIR/bin/:$PATH"
    which make.bat > /dev/null 2>&1 && alias make="make.bat"

    alias dir="ls --color"
else
    alias ls="dir --color=auto"
    # suse aliases dir to ls -l
    alias dir > /dev/null 2> /dev/null && alias dir="ls --color"
fi


if [ ! "${BASH_VERSINFO[5]/solaris/}" != "${BASH_VERSINFO[5]}" ]; then # not in solaris
    alias emacs="emacs -nw"
fi

[ -r "$WEBSITE_DIR/himinbi.org/odin/config/muttrc" ] && alias mutt="mutt -F \"$WEBSITE_DIR/himinbi.org/odin/config/muttrc\""

[ -e /usr/local/java/lib/ant/bin/ant ] && alias ant="/usr/local/java/lib/ant/bin/ant"
[ -e /Developer/Java/Ant/bin/ant ] && alias ant="/Developer/Java/Ant/bin/ant"
alias recent="last -ad | head -n 15"
alias mailq="sudo mailq -Ac; sudo mailq"
alias putmail="sudo /usr/sbin/sendmail -q"
alias getmail="fetchmail --ssl --all honors.tntech.edu"
alias getextramail="fetchmail --ssl --keep --folder mail/orgs/cor,mail/dorks,mail/orgs/mentor --protocol IMAP honors.tntech.edu"

alias tunnel="ssh -L :2222:wholcomb.intranet:22 root@secure.mpp.org"
alias getwork="rsync --recursive --verbose --progress --links --rsh ssh\\ -p2222 wholcomb@localhost2:Public ~/"
alias getmusic="rsync --recursive --verbose --progress --links --rsh ssh\\ -p2222 wholcomb@localhost2:Music/ /usr/share/music/"

PROG_DIR="$WEBSITE_DIR/pcvs.org/mr/will"

alias getpics="$PROG_DIR/bin/getpics.sh"
alias forward="$PROG_DIR/bin/forward.sh"
alias days="date=\$(date +%Y/%m/%d); \
            passed=\$(perl $PROG_DIR/bin/days.pl 2003/6/24 \$date); \
            left=\$(perl $PROG_DIR/bin/days.pl \$date 2005/9/16); \
            percent=\$(( \$passed * 10000 / (\$passed + \$left) )); \
            percent=\${percent:0:\$(( \${#percent} - 2 ))}.\${percent#??}; \
            echo \$date - you have been here \$passed days and have \$left left \(\$percent%\)"

alias syncfiles="find \"$WEBSITE_DIR\" \\( -name \"*~\" -or -name \".*~\" \\) -printf \"\\\"%p\\\"\\n\" | xargs rm -v; \
                 rsync --rsh=ssh --partial --progress --verbose --recursive \
                    --delete-after --archive --compress \
                    --exclude=Thumbs.db --exclude=\".#*\" --exclude=\"#*\" --exclude=.xvpics \
                    --exclude=\"sites/awstats/reports/\" --exclude=sites/awstats/data/ \
                    --exclude=\"sites/pcvs.org/mr/links.html\" \
                    --exclude=roster/ --exclude=carl/ \
                    --exclude=\"sites/gallery\" --exclude=\"sites/albums\" \
                    \"$WEBSITE_DIR\" will@himinbi.org:"
